<?php
/*
 * This is part of jcubic/expression package
 * Copyright (c) 2024 Jakub T. Jankiewicz <https://jcu.bi>
 * Released under MIT license
 *
 * This is Expression class witch is an Adapter for the Parser generated by PEG
 */

namespace jcubic;

class Expression {
    private $constants;
    public $variables = [];
    public $functions = [];
    public $suppress_errors = false;
    private $expr = null;
    function __construct() {
        $this->constants = ["e" => exp(1), "pi" => M_PI];
    }
    function evaluate($expr) {
        if (empty(trim($expr))) {
            return null;
        }
        $this->expr = new Parser($expr, $this->variables, $this->constants, $this->functions);
        try {
            $res = $this->expr->match_Start();
        } catch (\Exception $e) {
            throw new \Exception($e->getMessage() . " in expression: " . $expr);
        }
        if ($res === FALSE) {
            throw new \Exception("invalid syntax $expr");
        }
        $this->variables = &$this->expr->variables;
        $this->functions = &$this->expr->functions;
        if ($this->expr->is_typed($res['val'])) {
            return $res['val']['value'];
        }
        return $res['val'];
    }
}
